"""orbit_video: the hero image as first and last frame of a 360-degree orbit,
generated by MiniMax H3 FL2V in giro's ComfyUI on one GPU.

With model "wan22-control" (the proxy orbit) it is instead the proxy stage's splat rendered as
depth along a known camera path (giro.path), repainted by Wan 2.2 Fun Control with the hero as
the first frame and the appearance reference; the cameras go to cameras.json, frame by frame."""

from __future__ import annotations

import asyncio
import io
import json
import shutil
import subprocess
import time
from collections.abc import AsyncIterator, Sequence
from pathlib import Path
from typing import Any

import aiohttp
import numpy as np
from PIL import Image

from giro import path as campath
from giro import workflows
from giro.comfy import ComfyClient, ComfyError, Done, Event, NodeStarted, Preview, Progress, server
from giro.hero import fit_to_aspect
from giro.stages.base import Ctx, Stage, StageFailed

# MiniMax H3 weights stream from system RAM, so it runs with less free VRAM
# than its ~20 GB footprint; this is the threshold for preferring a GPU.
ORBIT_VRAM_MB = 20_000


async def events(comfy: ComfyClient, prompt: dict[str, Any], ctx: Ctx) -> AsyncIterator[Event]:
    """Run `prompt`, yielding its events; a cancel interrupts ComfyUI and raises Cancelled."""
    async def interrupt_on_cancel() -> None:
        # Events can be ~15 s apart while sampling; don't wait for one to notice.
        while not ctx.is_cancelled():
            await asyncio.sleep(0.5)
        await comfy.interrupt()

    watcher = asyncio.create_task(interrupt_on_cancel())
    try:
        async for event in comfy.run(prompt):
            if ctx.is_cancelled():
                await comfy.interrupt()
                ctx.check_cancelled()
            yield event
    finally:
        watcher.cancel()


def opts_path(params: dict[str, Any]) -> str:
    """The proxy orbit's path preset."""
    return params.get("path", OrbitVideo.path_defaults["path"])


def output_images(done: Done, node: str | None = None) -> list[dict[str, str]]:
    """A finished prompt's saved images (only node `node`'s, if given), in frame order."""
    outputs = [done.outputs.get(node, {})] if node else list(done.outputs.values())
    return sorted((img for out in outputs for img in out.get("images", [])), key=lambda x: x["filename"])


def prepare_hero(image: Path, attempt: Path, width: int, height: int, crop: Sequence[float] | None = None) -> float:
    """Write attempt/hero/hero.png at the video's aspect ratio (from the `crop` region of the image,
    see fit_to_aspect); returns the fraction cropped away."""
    hero, cropped_frac = fit_to_aspect(image, width, height, crop)
    path = attempt / "hero" / "hero.png"
    path.parent.mkdir(parents=True, exist_ok=True)
    data = io.BytesIO()
    hero.save(data, format="PNG")
    # Rewriting identical bytes would change the mtime and invalidate every stage downstream.
    if not path.exists() or path.read_bytes() != data.getvalue():
        path.write_bytes(data.getvalue())
    return cropped_frac


class OrbitVideo(Stage):
    name = "orbit_video"
    defaults = {
        "prompt": workflows.ORBIT_PROMPT,
        "width": 768,
        "height": 1024,
        "length": 158,  # sweep 20260929: same GPU time per passing seed as 124, 22% more views
        "steps": 20,
        "seed": None,  # required; the caller picks it so the attempt is reproducible
        "keep_loaded": False,
    }
    # Also read when a run sets them, and left out of `defaults` so older attempts keep their
    # stage key: "lora" (a file under ComfyUI's loras folder; null for none), "lora_strength"
    # (default 1.0), "model" ("h3", the default, "wan22" or "wan22-control") and, for Wan's low-noise
    # model, "lora_low". For "wan22-control": "path" (a giro.path preset, default "spiral"), "turns"
    # (default 2), "pitch_end" (default 45 degrees) and "clips": more clips continuing the path,
    # each {"frames", "turns", "pitch_end", "distance" (times the hero's), "aim" (see _cameras)},
    # starting on the previous clip's last frame; "refine": {"width", "height", "sigma" (0.35),
    # "steps" (8)}, a second pass over each clip at that size (_refine); "init": {"sigma" (0.9),
    # "steps" (16)}, each clip starts from the proxy's color render noised to sigma, not from noise;
    # "upscale": {"scale" (2), "model", "color" ("lab")}, SeedVR2 over each clip (_upscale); on by
    # default (proxy_upscale), null turns it off.
    # With H3 and no "lora" given, the 360 orbit LoRA is used, with the prompt it was trained on
    # in place of giro's stock prompt (docs/FINDINGS.md, "Orbit videos").
    tuned = {"lora": "h3/minimax_h3_flf2v_orbit360_pablodawson_v1.safetensors"}
    inputs = ("hero/hero.png",)
    outputs = ("frames_raw", "video.mp4", "orbit.json")
    gpu_mb = ORBIT_VRAM_MB
    path_defaults = {"path": "spiral", "turns": 2.0, "pitch_end": 45.0}
    # The proxy orbit upscales its frames twice with SeedVR2 unless "upscale" is given (null: off).
    proxy_upscale = {"scale": 2.0}
    extra_params = ("lora", "lora_strength", "lora_low", "model", "clips", "refine", "init", "upscale", *path_defaults)

    def inputs_for(self, params: dict[str, Any]) -> tuple[str, ...]:
        if params.get("model") == "wan22-control":
            return self.inputs + ("proxy/proxy.ply", "proxy/proxy.json")
        return self.inputs

    def run(self, attempt: Path, params: dict[str, Any], ctx: Ctx) -> None:
        if params["seed"] is None:
            raise StageFailed("orbit_video needs a seed")
        try:
            asyncio.run(self._generate(attempt, params, ctx))
        except ComfyError as e:
            ctx.check_cancelled()  # giro's own interrupt, not a ComfyUI failure
            raise StageFailed(f"ComfyUI: {e}") from None
        except aiohttp.ClientConnectionError:
            ctx.check_cancelled()
            raise StageFailed("lost the connection to ComfyUI (it stopped or crashed); Retry runs this step again") from None

    async def _generate(self, attempt: Path, params: dict[str, Any], ctx: Ctx) -> None:
        frames_dir, previews_dir = attempt / "frames_raw", attempt / "previews"
        for d in (frames_dir, previews_dir, attempt / "proxy_render", attempt / "frames_base", attempt / "frames_upscale_in"):
            if d.exists():
                shutil.rmtree(d)
        frames_dir.mkdir()
        previews_dir.mkdir()
        device = ctx.gpu if ctx.gpu is not None else server.pick_gpu(ORBIT_VRAM_MB)
        ctx.log(f"GPU {device}: starting ComfyUI if needed")
        with await asyncio.to_thread(server.Lease, device) as lease:
            await self._sample(lease.url, device, attempt, params, ctx)

    async def _sample(self, url: str, device: int, attempt: Path, params: dict[str, Any], ctx: Ctx) -> None:
        frames_dir, previews_dir = attempt / "frames_raw", attempt / "previews"
        model = params.get("model") or "h3"
        length = workflows.snap_length(params["length"], model)
        loras = {"lora": params["lora"] if "lora" in params else (self.tuned["lora"] if model == "h3" else None),
                 "lora_low": params.get("lora_low")}
        text = params["prompt"]
        if loras["lora"] == self.tuned["lora"] and text == workflows.ORBIT_PROMPT:
            text = workflows.FROZEN_ORBIT_PROMPT
        stamp = f"giro/{time.strftime('%Y%m%d-%H%M%S')}-{params['seed']}"
        wf = {
            "prompt": text, "width": params["width"], "height": params["height"],
            "length": length, "seed": params["seed"], "steps": params["steps"],
            "output_prefix": f"{stamp}/frame",
        }
        cameras: dict[str, Any] | None = None
        clips: list[list[campath.PathCamera]] = [[]]
        if model == "wan22-control":
            cameras, clips = self._cameras(attempt, params, length)
            if text == workflows.ORBIT_PROMPT:
                wf["prompt"] = workflows.PROXY_ORBIT_PROMPT
            wf |= {"proxy": str((attempt / "proxy" / "proxy.ply").resolve()), "depth_prefix": f"{stamp}/depth"}
        render_dir = attempt / "proxy_render"
        ranges: list[tuple[int, int]] = []  # each clip's first frame and length
        n_frames = 0  # frames written so far, over all clips
        seconds = 0.0
        async with ComfyClient(url) as comfy:
            try:
                hero = await comfy.upload_image(attempt / "hero" / "hero.png")
                start = hero
                n_previews = 0
                for k, clip in enumerate(clips):
                    # A chained clip starts on the previous clip's last frame (and camera); that
                    # frame is already written, so its first frame is dropped.
                    offset = n_frames - (1 if k else 0)
                    wf_k = wf | {"image": hero}
                    if cameras:
                        wf_k |= {"cameras": json.dumps([c.render_json() for c in clip]),
                                 "silhouette_paths": json.dumps([str((render_dir / "silhouettes" / f"{offset + i:05d}.png").resolve())
                                                                 for i in range(len(clip))]),
                                 "length": len(clip), "output_prefix": f"{stamp}/clip{k}", "depth_prefix": f"{stamp}/depth{k}"}
                    ctx.log(f"queued{f' clip {k + 1}/{len(clips)}' if len(clips) > 1 else ''}: {params['width']}x{params['height']}, "
                            f"{wf_k['length']} frames, {params['steps']} steps, seed {params['seed']}")
                    t0 = time.monotonic()
                    done: Done | None = None
                    if cameras and params.get("init"):
                        # Start from the proxy's color render, noised to init's sigma, instead of noise.
                        init = params["init"]
                        prompt = workflows.build_refine(
                            params["width"], params["height"], float(init.get("sigma", 0.9)), int(init.get("steps", 16)),
                            from_proxy=True, silhouette_paths=wf_k["silhouette_paths"], depth_prefix=wf_k["depth_prefix"],
                            image=hero, start=start, prompt=wf_k["prompt"], seed=params["seed"], proxy=wf_k["proxy"],
                            cameras=wf_k["cameras"], length=len(clip), output_prefix=wf_k["output_prefix"])
                    else:
                        prompt = workflows.build_orbit(model, **wf_k)
                    if cameras and k == 0 and opts_path(params) == "loop":
                        # The loop comes back to the hero's camera: the hero is its last frame too.
                        prompt["condition"]["inputs"]["end_image"] = ["hero", 0]
                    if cameras and start != hero and not params.get("init"):
                        prompt["start"] = {"class_type": "LoadImage", "inputs": {"image": start, "upload": "image"}}
                        prompt["condition"]["inputs"]["start_image"] = ["start", 0]
                    elif cameras and params.get("init") and start == hero:
                        prompt["condition"]["inputs"]["start_image"] = ["hero", 0]
                        del prompt["start"]
                    strength = float(params.get("lora_strength") or 1.0)
                    for key, loader in (("lora", "unet"), ("lora_low", "unet_low")):
                        if loras[key]:
                            workflows.with_lora(prompt, loras[key], strength, loader)
                            ctx.log(f"LoRA {loras[key]}")
                    async for event in events(comfy, prompt, ctx):
                        if isinstance(event, NodeStarted):
                            ctx.log(f"node {event.node} ({event.class_type}) at {time.monotonic() - t0:.0f}s")
                        elif isinstance(event, Progress):
                            # Sampling dominates; decode and saving fill the last 10%.
                            ctx.progress(0.9 * (k + event.value / event.max) / len(clips),
                                         f"{f'clip {k + 1}/{len(clips)}, ' if len(clips) > 1 else ''}step {event.value}/{event.max}")
                        elif isinstance(event, Preview):
                            n_previews += 1
                            ext = "png" if event.mime == "image/png" else "jpg"
                            path = previews_dir / f"{n_previews:03d}.{ext}"
                            path.write_bytes(event.image)
                            ctx.preview(path)
                        elif isinstance(event, Done):
                            done = event
                    seconds += time.monotonic() - t0
                    assert done is not None
                    images = output_images(done, "frames" if cameras else None)
                    if cameras and len(images) != len(clip):
                        raise StageFailed(f"Wan returned {len(images)} frames for {len(clip)} cameras")
                    if cameras and k == 0:
                        await self._check_first_frame(comfy, images[0], attempt, ctx)
                    ctx.progress(0.9 * (k + 1) / len(clips), f"downloading {len(images)} frames")
                    for i, img in enumerate(images):
                        if k and i == 0:
                            continue
                        await comfy.download(img, frames_dir / f"{offset + i:05d}.png")
                    if cameras:
                        (render_dir / "depth").mkdir(parents=True, exist_ok=True)
                        for i, img in enumerate(output_images(done, "depth_frames")):
                            await comfy.download(img, render_dir / "depth" / f"{offset + i:05d}.png")
                    n_frames = offset + len(images)
                    ranges.append((offset, len(images)))
                    if k + 1 < len(clips):
                        start = await comfy.upload_image(frames_dir / f"{n_frames - 1:05d}.png")
                if cameras and params.get("refine"):
                    seconds += await self._refine(comfy, attempt, hero, clips, ranges, wf["prompt"], params, ctx)
                    cameras |= {"width": params["refine"]["width"], "height": params["refine"]["height"]}
                upscale = params["upscale"] if "upscale" in params else self.proxy_upscale
                if cameras and upscale:
                    size, took = await self._upscale(comfy, attempt, ranges, cameras["width"], cameras["height"],
                                                     params | {"upscale": upscale}, ctx)
                    seconds += took
                    cameras |= {"width": size[0], "height": size[1]}
            finally:
                if not params["keep_loaded"]:
                    # Hand the VRAM back for the next job on this GPU (or another ComfyUI on it).
                    await comfy.free()

        await asyncio.to_thread(subprocess.run, [
            "ffmpeg", "-loglevel", "error", "-y", "-framerate", "16" if model.startswith("wan22") else "24", "-i", str(frames_dir / "%05d.png"),
            "-c:v", "libx264", "-crf", "16", "-pix_fmt", "yuv420p", str(attempt / "video.mp4"),
        ], check=True)
        if cameras:
            if n_frames != len(cameras["frames"]):
                raise StageFailed(f"wrote {n_frames} frames for {len(cameras['frames'])} cameras")
            (attempt / "cameras.json").write_text(json.dumps(cameras, indent=1) + "\n")
        (attempt / "orbit.json").write_text(json.dumps({
            "params": {k: v for k, v in wf.items() if k != "image"} | {k: v for k, v in loras.items() if v},
            "model": model, "gpu": device,
            "seconds": round(seconds, 1), "frames": n_frames,
        }, indent=2) + "\n")
        ctx.metric("seed", params["seed"])
        ctx.metric("gpu", device)
        if cameras:
            ctx.metric("path", cameras["preset"])
        ctx.metric("n_frames", n_frames)
        ctx.metric("seconds", round(seconds, 1))
        ctx.progress(1.0, f"{n_frames} frames in {seconds:.0f}s")

    async def _check_first_frame(self, comfy: ComfyClient, image: dict[str, str], attempt: Path, ctx: Ctx) -> None:
        """The first frame is pinned to the hero (31 dB against it on the first runs). Once, on
        Oct 4, Wan returned 81 frames of pure noise (about 10 dB); stop there instead of masking
        and training on noise."""
        first = attempt / "frames_raw" / ".first.png"
        await comfy.download(image, first)
        frame = Image.open(first).convert("RGB")
        hero = Image.open(attempt / "hero" / "hero.png").convert("RGB").resize(frame.size, Image.Resampling.LANCZOS)
        first.unlink()
        mse = float(np.mean((np.asarray(frame, dtype=np.float64) - np.asarray(hero, dtype=np.float64)) ** 2))
        psnr = 10 * np.log10(255.0**2 / max(mse, 1e-6))
        ctx.metric("first_frame_psnr", round(psnr, 2))
        if psnr < 20.0:
            raise StageFailed(f"the video's first frame does not match the hero ({psnr:.1f} dB): the video model "
                              "returned noise or a broken clip; Retry runs it again")

    async def _refine(self, comfy: ComfyClient, attempt: Path, hero: str, clips: list[list[campath.PathCamera]],
                      ranges: list[tuple[int, int]], text: str, params: dict[str, Any], ctx: Ctx) -> float:
        """The refine pass: each clip again at refine's width x height, from its sigma. The first
        pass's frames move to frames_base/; returns the seconds it took."""
        spec = params["refine"]
        frames_dir, base = attempt / "frames_raw", attempt / "frames_base"
        if base.exists():
            shutil.rmtree(base)
        frames_dir.rename(base)
        frames_dir.mkdir()
        t0 = time.monotonic()
        stamp = f"giro/{time.strftime('%Y%m%d-%H%M%S')}-{params['seed']}"
        for k, ((offset, n), clip) in enumerate(zip(ranges, clips)):
            # The chained clips' shared first frame: refined already, it pins the next clip.
            start = hero if k == 0 else await comfy.upload_image(frames_dir / f"{offset:05d}.png")
            prompt = workflows.build_refine(
                spec["width"], spec["height"], float(spec.get("sigma", 0.35)), int(spec.get("steps", 8)),
                frames=json.dumps([str((base / f"{offset + i:05d}.png").resolve()) for i in range(n)]),
                image=hero, start=start, prompt=text, seed=params["seed"],
                proxy=str((attempt / "proxy" / "proxy.ply").resolve()),
                cameras=json.dumps([c.render_json() for c in clip]), length=n, output_prefix=f"{stamp}/refine{k}")
            ctx.log(f"refining clip {k + 1}/{len(clips)} at {spec['width']}x{spec['height']} from sigma {spec.get('sigma', 0.35)}")
            done: Done | None = None
            async for event in events(comfy, prompt, ctx):
                if isinstance(event, Progress):
                    ctx.progress(0.9 + 0.08 * (k + event.value / event.max) / len(clips),
                                 f"refining clip {k + 1}/{len(clips)}, step {event.value}/{event.max}")
                elif isinstance(event, Done):
                    done = event
            assert done is not None
            images = output_images(done, "frames")
            if len(images) != n:
                raise StageFailed(f"the refine pass returned {len(images)} frames for {n}")
            for i, img in enumerate(images):
                if k and i == 0:
                    continue
                await comfy.download(img, frames_dir / f"{offset + i:05d}.png")
        return time.monotonic() - t0

    async def _upscale(self, comfy: ComfyClient, attempt: Path, ranges: list[tuple[int, int]], width: int, height: int,
                       params: dict[str, Any], ctx: Ctx) -> tuple[tuple[int, int], float]:
        """SeedVR2 over each clip's frames, `scale` times their size (multiples of 16). The frames
        before it move to frames_base/ (unless a refine pass already put the first pass there);
        returns the new size and the seconds it took."""
        spec = params["upscale"]
        scale = float(spec.get("scale", 2.0))
        size = (round(width * scale / 16) * 16, round(height * scale / 16) * 16)
        frames_dir = attempt / "frames_raw"
        source = attempt / "frames_upscale_in"
        if source.exists():
            shutil.rmtree(source)
        frames_dir.rename(source)
        frames_dir.mkdir()
        t0 = time.monotonic()
        stamp = f"giro/{time.strftime('%Y%m%d-%H%M%S')}-{params['seed']}"
        for k, (offset, n) in enumerate(ranges):
            # whole clips, so SeedVR2's temporal window sees each clip as the video it is
            first = offset if k == 0 else offset + 1
            names = [f"{i:05d}.png" for i in range(first, offset + n)]
            prompt = workflows.build("upscale_seedvr2", frames=json.dumps([str((source / f).resolve()) for f in names]),
                                     width=size[0], height=size[1], unet=spec.get("model", "seedvr2/seedvr2_7b_fp8_e4m3fn.safetensors"),
                                     color=spec.get("color", "lab"), seed=params["seed"], output_prefix=f"{stamp}/upscale{k}")
            ctx.log(f"upscaling clip {k + 1}/{len(ranges)} to {size[0]}x{size[1]} (SeedVR2)")
            ctx.progress(0.98, f"upscaling clip {k + 1}/{len(ranges)}")
            done: Done | None = None
            async for event in events(comfy, prompt, ctx):
                if isinstance(event, Done):
                    done = event
            assert done is not None
            images = output_images(done, "save")
            if len(images) != len(names):
                raise StageFailed(f"SeedVR2 returned {len(images)} frames for {len(names)}")
            for name, img in zip(names, images):
                await comfy.download(img, frames_dir / name)
        base = attempt / "frames_base"
        if base.exists():
            shutil.rmtree(source)  # the refine pass's input is the one to keep
        else:
            source.rename(base)
        return size, time.monotonic() - t0

    def _cameras(self, attempt: Path, params: dict[str, Any], length: int
                 ) -> tuple[dict[str, Any], list[list[campath.PathCamera]]]:
        """The proxy orbit's camera path, from the hero camera the proxy stage fitted: the preset's
        clip, then each of `clips` continuing from where the one before ended. Returns cameras.json
        (one camera per written frame) and the cameras of each clip."""
        proxy = json.loads((attempt / "proxy" / "proxy.json").read_text())
        hero = campath.PathCamera.from_json(proxy["hero_camera"])
        lo, hi = (np.asarray(b, dtype=float) for b in proxy["bounds"])
        opts = {k: params.get(k, v) for k, v in self.path_defaults.items()}
        clips = [campath.plan(hero, opts["path"], length, turns=float(opts["turns"]), pitch_end=float(opts["pitch_end"]))]
        for spec in params.get("clips") or []:
            # distance: times the hero's; aim: the target's height above the proxy's middle, in
            # proxy heights (the splat frame's y points down)
            target = None
            if "aim" in spec:
                target = (hero.target[0], (lo[1] + hi[1]) / 2 - float(spec["aim"]) * (hi[1] - lo[1]), hero.target[2])
            clips.append(campath.segment(
                clips[-1][-1], workflows.snap_length(int(spec.get("frames", length)), "wan22"),
                turns=float(spec.get("turns", 1.0)), pitch_end=spec.get("pitch_end"),
                distance_end=hero.distance * float(spec["distance"]) if "distance" in spec else None, target_end=target))
        frames = clips[0] + [c for clip in clips[1:] for c in clip[1:]]
        return {"preset": opts["path"], "turns": opts["turns"], "pitch_end": opts["pitch_end"],
                "clips": params.get("clips") or [], "width": params["width"], "height": params["height"],
                "hero": hero.to_json(), "frames": [c.to_json() for c in frames]}, clips
