"""orbit_video: the hero image as first and last frame of a 360-degree orbit,
generated by MiniMax H3 FL2V in giro's ComfyUI on one GPU."""

from __future__ import annotations

import asyncio
import io
import json
import shutil
import subprocess
import time
from collections.abc import AsyncIterator
from pathlib import Path
from typing import Any

import aiohttp

from giro import workflows
from giro.comfy import ComfyClient, ComfyError, Done, Event, NodeStarted, Preview, Progress, server
from giro.hero import fit_to_aspect
from giro.stages.base import Ctx, Stage, StageFailed

# MiniMax H3 weights stream from system RAM, so it runs with less free VRAM
# than its ~20 GB footprint; this is the threshold for preferring a GPU.
ORBIT_VRAM_MB = 20_000


async def events(comfy: ComfyClient, prompt: dict[str, Any], ctx: Ctx) -> AsyncIterator[Event]:
    """Run `prompt`, yielding its events; a cancel interrupts ComfyUI and raises Cancelled."""
    async def interrupt_on_cancel() -> None:
        # Events can be ~15 s apart while sampling; don't wait for one to notice.
        while not ctx.is_cancelled():
            await asyncio.sleep(0.5)
        await comfy.interrupt()

    watcher = asyncio.create_task(interrupt_on_cancel())
    try:
        async for event in comfy.run(prompt):
            if ctx.is_cancelled():
                await comfy.interrupt()
                ctx.check_cancelled()
            yield event
    finally:
        watcher.cancel()


def output_images(done: Done) -> list[dict[str, str]]:
    """A finished prompt's saved images, in frame order."""
    return sorted((img for out in done.outputs.values() for img in out.get("images", [])), key=lambda x: x["filename"])


def prepare_hero(image: Path, attempt: Path, width: int, height: int) -> float:
    """Write attempt/hero/hero.png at the video's aspect ratio; returns the fraction cropped away."""
    hero, cropped_frac = fit_to_aspect(image, width, height)
    path = attempt / "hero" / "hero.png"
    path.parent.mkdir(parents=True, exist_ok=True)
    data = io.BytesIO()
    hero.save(data, format="PNG")
    # Rewriting identical bytes would change the mtime and invalidate every stage downstream.
    if not path.exists() or path.read_bytes() != data.getvalue():
        path.write_bytes(data.getvalue())
    return cropped_frac


class OrbitVideo(Stage):
    name = "orbit_video"
    defaults = {
        "prompt": workflows.ORBIT_PROMPT,
        "width": 768,
        "height": 1024,
        "length": 158,  # sweep 20260929: same GPU time per passing seed as 124, 22% more views
        "steps": 20,
        "seed": None,  # required; the caller picks it so the attempt is reproducible
        "keep_loaded": False,
    }
    inputs = ("hero/hero.png",)
    outputs = ("frames_raw", "video.mp4", "orbit.json")
    gpu_mb = ORBIT_VRAM_MB

    def run(self, attempt: Path, params: dict[str, Any], ctx: Ctx) -> None:
        if params["seed"] is None:
            raise StageFailed("orbit_video needs a seed")
        try:
            asyncio.run(self._generate(attempt, params, ctx))
        except ComfyError as e:
            ctx.check_cancelled()  # giro's own interrupt, not a ComfyUI failure
            raise StageFailed(f"ComfyUI: {e}") from None
        except aiohttp.ClientConnectionError:
            ctx.check_cancelled()
            raise StageFailed("lost the connection to ComfyUI (it stopped or crashed); Retry runs this step again") from None

    async def _generate(self, attempt: Path, params: dict[str, Any], ctx: Ctx) -> None:
        frames_dir, previews_dir = attempt / "frames_raw", attempt / "previews"
        for d in (frames_dir, previews_dir):
            if d.exists():
                shutil.rmtree(d)
            d.mkdir()
        device = ctx.gpu if ctx.gpu is not None else server.pick_gpu(ORBIT_VRAM_MB)
        ctx.log(f"GPU {device}: starting ComfyUI if needed")
        with await asyncio.to_thread(server.Lease, device) as lease:
            await self._sample(lease.url, device, attempt, params, ctx)

    async def _sample(self, url: str, device: int, attempt: Path, params: dict[str, Any], ctx: Ctx) -> None:
        frames_dir, previews_dir = attempt / "frames_raw", attempt / "previews"
        length = workflows.snap_length(params["length"])
        wf = {
            "prompt": params["prompt"], "width": params["width"], "height": params["height"],
            "length": length, "seed": params["seed"], "steps": params["steps"],
            "output_prefix": f"giro/{time.strftime('%Y%m%d-%H%M%S')}-{params['seed']}/frame",
        }
        async with ComfyClient(url) as comfy:
            try:
                wf["image"] = await comfy.upload_image(attempt / "hero" / "hero.png")
                ctx.log(f"queued: {params['width']}x{params['height']}, {length} frames, "
                        f"{params['steps']} steps, seed {params['seed']}")
                t0 = time.monotonic()
                n_previews = 0
                done: Done | None = None
                async for event in events(comfy, workflows.build("orbit_video", **wf), ctx):
                    if isinstance(event, NodeStarted):
                        ctx.log(f"node {event.node} ({event.class_type}) at {time.monotonic() - t0:.0f}s")
                    elif isinstance(event, Progress):
                        # Sampling dominates; decode and saving fill the last 10%.
                        ctx.progress(0.9 * event.value / event.max, f"step {event.value}/{event.max}")
                    elif isinstance(event, Preview):
                        n_previews += 1
                        ext = "png" if event.mime == "image/png" else "jpg"
                        path = previews_dir / f"{n_previews:03d}.{ext}"
                        path.write_bytes(event.image)
                        ctx.preview(path)
                    elif isinstance(event, Done):
                        done = event
                seconds = time.monotonic() - t0
                assert done is not None
                images = output_images(done)
                ctx.progress(0.95, f"downloading {len(images)} frames")
                for i, img in enumerate(images):
                    await comfy.download(img, frames_dir / f"{i:05d}.png")
            finally:
                if not params["keep_loaded"]:
                    # Hand the VRAM back for the next job on this GPU (or another ComfyUI on it).
                    await comfy.free()

        await asyncio.to_thread(subprocess.run, [
            "ffmpeg", "-loglevel", "error", "-y", "-framerate", "24", "-i", str(frames_dir / "%05d.png"),
            "-c:v", "libx264", "-crf", "16", "-pix_fmt", "yuv420p", str(attempt / "video.mp4"),
        ], check=True)
        (attempt / "orbit.json").write_text(json.dumps({
            "params": {k: v for k, v in wf.items() if k != "image"}, "gpu": device,
            "seconds": round(seconds, 1), "frames": len(images),
        }, indent=2) + "\n")
        ctx.metric("seed", params["seed"])
        ctx.metric("gpu", device)
        ctx.metric("n_frames", len(images))
        ctx.metric("seconds", round(seconds, 1))
        ctx.progress(1.0, f"{len(images)} frames in {seconds:.0f}s")
