"""A job: one image, several orbit seeds, the best attempt picked automatically.

Each attempt runs every stage in its own directory, jobs/<id>/attempts/<seed>/.
Attempts that the gate (or an earlier stage) rejects are replaced by a new
seed until `want` attempts pass or `max_attempts` have been made. Passing
attempts are ranked by held-out eval PSNR. Stages that need a GPU lease one
from a shared pool, so videos, poses and training overlap across both GPUs.

The job's state lives in job.json and is rewritten as attempts progress, so
an interrupted job can be resumed: finished stages are skipped. The same
skipping makes every later change cheap: give an attempt new params (a
per-attempt override, e.g. the crop's tau) and queue it again, and only the
stages whose inputs or params changed run.
"""

from __future__ import annotations

import asyncio
import fcntl
import itertools
import json
import random
import shutil
import signal
import threading
import time
from collections.abc import Callable
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from giro import stages
from giro.comfy import server
from giro.scheduler import GpuPool
from giro.stages.orbit import prepare_hero

TERMINAL = {"passed", "rejected", "error", "discarded"}
# Attempts that count toward `want`: the others are replaced by a new seed while the budget lasts.
ALIVE = {"queued", "running", "passed"}


@dataclass
class JobSpec:
    image: str
    want: int = 3           # passing attempts to aim for
    max_attempts: int = 6   # total seeds, rerolls included
    seeds: list[int] = field(default_factory=list)  # tried first, then random ones
    orbit: dict[str, Any] = field(default_factory=dict)            # orbit_video params (not seed)
    params: dict[str, dict[str, Any]] = field(default_factory=dict)  # per-stage overrides
    video_gpus: list[int] = field(default_factory=lambda: [1])      # GPU 0 drives the desktop
    post_gpus: list[int] = field(default_factory=lambda: [0, 1])
    use_edit: bool = False  # orbit input/edited.png (the edit stage's output) instead of source.png
    crop: list[float] | None = None  # region of the image the hero keeps, (left, top, right, bottom) in 0-1; None: centered


@dataclass
class Attempt:
    seed: int
    status: str = "queued"  # queued, running, passed, rejected, error, cancelled, discarded
    stage: str = ""
    reason: str = ""
    gpus: dict[str, int] = field(default_factory=dict)
    eval_psnr: float | None = None
    gate: dict[str, Any] = field(default_factory=dict)
    seconds: float | None = None
    gaussians: int | None = None  # in the exported splat
    params: dict[str, dict[str, Any]] = field(default_factory=dict)  # per-stage overrides over the job's
    override: str | None = None  # "pass" or "fail": the user's verdict over the gate's
    filled: list[str] = field(default_factory=list)  # gaps of the orbit regenerated by gapfill
    poses: str = "colmap"  # whose cameras it trained on: "colmap", or "fallback" (Depth Anything 3 + COLMAP)

    def stage_params(self, spec: JobSpec, stage: str) -> dict[str, Any]:
        return spec.params.get(stage, {}) | self.params.get(stage, {})


class Job:
    def __init__(self, path: Path, spec: JobSpec, attempts: list[Attempt] | None = None,
                 created: str | None = None):
        self.path = path
        self.spec = spec
        self.attempts = attempts or []
        self.created = created or time.strftime("%Y-%m-%dT%H:%M:%S")
        self.status = "running"  # or "draft": created, not started (e.g. while trying edits)
        self.ranking: list[int] = []
        # The optional background edit: {status: running|done|error, prompt, seed, fast, error}.
        self.edit: dict[str, Any] = {}
        self._lock = threading.Lock()
        self.on_save: Callable[[dict[str, Any]], None] | None = None  # called with job.json's content

    @property
    def id(self) -> str:
        return self.path.name

    @classmethod
    def create(cls, root: Path, spec: JobSpec, name: str | None = None) -> Job:
        image = Path(spec.image)
        job_id = f"{time.strftime('%Y%m%d-%H%M%S')}-{name or image.stem}"
        path = root / job_id
        for n in itertools.count(2):  # two jobs for one image in the same second
            if not path.exists():
                break
            path = root / f"{job_id}-{n}"
        (path / "input").mkdir(parents=True)
        shutil.copyfile(image, path / "input" / "source.png")
        job = cls(path, spec)
        job.save()
        return job

    @classmethod
    def load(cls, path: Path) -> Job:
        data = json.loads((path / "job.json").read_text())
        job = cls(path, JobSpec(**data["spec"]), [Attempt(**a) for a in data["attempts"]], data["created"])
        job.status, job.ranking = data.get("status", "running"), data.get("ranking", [])
        job.edit = data.get("edit", {})
        return job

    def attempt_dir(self, seed: int) -> Path:
        return self.path / "attempts" / str(seed)

    def attempt(self, seed: int) -> Attempt:
        for a in self.attempts:
            if a.seed == seed:
                return a
        raise KeyError(seed)

    def data(self) -> dict[str, Any]:
        return {
            "id": self.id, "created": self.created, "status": self.status,
            "spec": asdict(self.spec), "ranking": self.ranking,
            "best": self.ranking[0] if self.ranking else None,
            "attempts": [asdict(a) for a in self.attempts],
            "edit": self.edit,
        }

    def hero_source(self) -> Path:
        """The image the orbits start from: the edited one if the job uses it."""
        edited = self.path / "input" / "edited.png"
        return edited if self.spec.use_edit and edited.exists() else self.path / "input" / "source.png"

    def save(self) -> None:
        with self._lock:
            data = self.data()
            tmp = self.path / "job.json.tmp"
            tmp.write_text(json.dumps(data, indent=2) + "\n")
            tmp.replace(self.path / "job.json")
        if self.on_save:
            self.on_save(data)

    def rank(self) -> None:
        passed = [a for a in self.attempts if a.status == "passed" and a.override != "fail"]
        self.ranking = [a.seed for a in sorted(passed, key=lambda a: -(a.eval_psnr or 0.0))]
        best = self.path / "best"
        best.unlink(missing_ok=True)
        if self.ranking:
            best.symlink_to(Path("attempts") / str(self.ranking[0]))


class JobLocked(RuntimeError):
    """Another process (a CLI run or a second server) is running this job."""


def locked_elsewhere(path: Path) -> bool:
    """True if another process holds the job's run lock."""
    lock = path / "job.lock"
    if not lock.exists():
        return False
    with open(lock) as f:
        try:
            fcntl.flock(f, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            return True
        fcntl.flock(f, fcntl.LOCK_UN)
    return False


Log = Callable[[str], None]
Event = Callable[[dict[str, Any]], None]


class Runner:
    def __init__(self, job: Job, log: Log, pool: GpuPool | None = None, cancel: threading.Event | None = None,
                 on_event: Event | None = None):
        """Pass a shared `pool` and `cancel` to run several jobs at once (see run_jobs);
        the caller then owns Ctrl-C handling and stopping ComfyUI. `on_event` receives what
        the stages report (progress, metric, preview, log) as dicts; it may be called from
        a stage's worker thread."""
        self.job = job
        self.log = log
        self.on_event = on_event
        self.tasks: dict[asyncio.Task[None], Attempt] = {}
        self.running = False
        self._stop: set[int] = set()  # seeds to stop and discard
        spec = job.spec
        self.standalone = pool is None
        self.pool = pool or GpuPool(sorted(set(spec.video_gpus) | set(spec.post_gpus)))
        self.cancel = cancel or threading.Event()
        used = {a.seed for a in job.attempts}
        self._fresh_seeds = iter([s for s in spec.seeds if s not in used])

    def _next_seed(self) -> int:
        used = {a.seed for a in self.job.attempts}
        for seed in self._fresh_seeds:
            return seed
        while (seed := random.randrange(2**32)) in used:
            pass
        return seed

    async def run(self) -> Job:
        job = self.job
        lock = open(job.path / "job.lock", "w")
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            lock.close()
            self.running = False
            raise JobLocked(f"{job.id} is being run by another giro process") from None
        try:
            return await self._run_locked()
        finally:
            lock.close()  # releases the lock

    async def _run_locked(self) -> Job:
        job, spec = self.job, self.job.spec
        loop = asyncio.get_running_loop()
        if self.standalone:
            loop.add_signal_handler(signal.SIGINT, self._interrupt)
        job.status = "running"
        self.running = True
        tasks = self.tasks

        def top_up() -> None:
            # Keep `want` attempts alive (running or passed) until the budget runs out.
            while not self.cancel.is_set() and job.status != "error":
                alive = sum(a.status in ALIVE and a.override != "fail" for a in job.attempts)
                if alive >= spec.want or len(job.attempts) >= spec.max_attempts:
                    return
                attempt = Attempt(self._next_seed())
                job.attempts.append(attempt)
                if len(job.attempts) > spec.want:
                    self.log(f"s{attempt.seed}: reroll ({len(job.attempts)} of at most {spec.max_attempts} attempts)")
                self.launch(attempt)

        for attempt in job.attempts:  # resuming: finish what was started
            if attempt.status not in TERMINAL and not self.is_active(attempt):
                self.launch(attempt)
        top_up()
        job.save()
        try:
            while tasks:
                # Tasks launched meanwhile (launch() from outside) join on the next pass.
                done, _ = await asyncio.wait(list(tasks), return_when=asyncio.FIRST_COMPLETED)
                for task in done:
                    attempt = tasks.pop(task)
                    task.result()
                    if attempt.status == "error":
                        job.status = "error"
                        self.log(f"s{attempt.seed}: {attempt.stage} broke ({attempt.reason}); no more rerolls")
                top_up()
                job.rank()
                job.save()
        finally:
            self.running = False
            if self.standalone:
                loop.remove_signal_handler(signal.SIGINT)
                for g in self.pool.gpus:
                    server.stop_if_idle(g)

        if self.cancel.is_set():
            job.status = "cancelled"
        elif job.status != "error":
            job.status = "done" if job.ranking else "failed"
        job.save()
        return job

    def launch(self, attempt: Attempt) -> None:
        """Run (or rerun) an attempt. While run() is going, the attempt joins it."""
        if any(a is attempt for a in self.tasks.values()):
            raise RuntimeError(f"s{attempt.seed} is already running")
        self._stop.discard(attempt.seed)
        attempt.status = "queued"
        self.tasks[asyncio.create_task(self._run_attempt(attempt))] = attempt

    def is_active(self, attempt: Attempt) -> bool:
        return any(a is attempt for a in self.tasks.values())

    def stop(self, attempt: Attempt) -> None:
        """Stop a queued or running attempt; it ends as discarded."""
        self._stop.add(attempt.seed)

    def _emit(self, attempt: Attempt, kind: str, stage: str, **data: Any) -> None:
        if self.on_event:
            self.on_event({"type": kind, "job": self.job.id, "seed": attempt.seed, "stage": stage} | data)

    def _interrupt(self) -> None:
        if self.cancel.is_set():
            return
        self.log("cancelling: stopping running stages (giro job resume continues later)")
        self.cancel.set()

    async def _run_attempt(self, attempt: Attempt) -> None:
        job, spec = self.job, self.job.spec
        path = job.attempt_dir(attempt.seed)
        orbit = stages.ORBIT.defaults | spec.orbit
        # Inline (milliseconds): GPU requests must queue in launch order.
        prepare_hero(job.hero_source(), path, orbit["width"], orbit["height"], spec.crop)
        attempt.status, attempt.reason = "running", ""
        t0 = time.monotonic()
        stopped = lambda: self.cancel.is_set() or attempt.seed in self._stop  # noqa: E731
        root = job.path.resolve()

        def log(stage: str, msg: str) -> None:
            self.log(f"s{attempt.seed} {stage}: {msg}")
            self._emit(attempt, "log", stage, msg=msg)

        ctx = stages.Ctx(
            on_progress=self._progress(attempt), on_log=log, is_cancelled=stopped,
            on_metric=lambda st, name, value, step: self._emit(
                attempt, "metric", st, name=name, value=value, **({"step": step} if step is not None else {})),
            on_preview=lambda st, p: self._emit(attempt, "preview", st, path=str(Path(p).resolve().relative_to(root))),
            on_start=lambda st: self._emit(attempt, "start", st),
        )
        restart = True
        fallback_tried = False  # for the current COLMAP reconstruction
        while restart:  # once more after a pose fallback or gap fill; unchanged stages skip themselves
            restart = False
            for order, stage in enumerate(stages.PIPELINE):
                attempt.stage = stage.name
                job.save()
                if stage is stages.ORBIT:
                    params = spec.orbit | {"seed": attempt.seed}
                else:
                    params = attempt.stage_params(spec, stage.name)
                    if stage.name == "gate" and attempt.override == "pass":
                        params = params | {"enforce": False}  # keep the measurements, ignore the verdict
                try:
                    # A stage that will skip itself needs no GPU: a rerun after new params does not
                    # wait behind other attempts' videos for stages it reuses.
                    if stage.gpu_mb and not await asyncio.to_thread(stage.is_current, path, params):
                        prefs = spec.video_gpus if stage is stages.ORBIT else spec.post_gpus
                        ran = await self._execute_leased(attempt, stage, path, params, ctx, prefs, -order)
                    else:
                        ctx.gpu = None
                        ran = await asyncio.to_thread(stage.execute, path, params, ctx)
                except stages.Cancelled:
                    attempt.status = "discarded" if attempt.seed in self._stop else "cancelled"
                    return
                except stages.StageFailed as e:
                    if stopped():  # Ctrl-C also reaches the stage's subprocess
                        attempt.status = "discarded" if attempt.seed in self._stop else "cancelled"
                        return
                    if isinstance(e, stages.Rejected) and stage.name == "gate":
                        try:
                            if stages.poses.active_source(path) == "fallback":
                                # The fallback's cameras failed too: back to COLMAP's, so the gate's
                                # verdict (and a gap fill's plan) is about them again.
                                self.log(f"s{attempt.seed}: the gate rejected the pose fallback too; back to COLMAP's cameras")
                                stages.poses.activate(path, "colmap")
                                restart = True
                            elif not fallback_tried:
                                fallback_tried = True
                                restart = await self._try_fallback(attempt, path, ctx, -order)
                            if not restart:
                                restart = await self._fill_gaps(attempt, path, ctx, -order)
                        except stages.Cancelled:
                            attempt.status = "discarded" if attempt.seed in self._stop else "cancelled"
                            return
                        if restart:
                            break
                    # Rejected: the video is bad, so reroll. Anything else is a fault in giro or
                    # the machine, and a new seed would only fail the same way.
                    attempt.status = "rejected" if isinstance(e, stages.Rejected) else "error"
                    attempt.stage = stage.name  # not the fallback or gap fill that ran after the gate's verdict
                    attempt.reason = str(e)
                    self.log(f"s{attempt.seed}: {'REJECTED' if attempt.status == 'rejected' else 'ERROR'} at {stage.name}: {e}")
                    break
                except Exception as e:  # noqa: BLE001 - reported on the attempt, not raised through the job
                    attempt.status, attempt.reason = "error", f"{type(e).__name__}: {e}"
                    self.log(f"s{attempt.seed}: ERROR at {stage.name}: {attempt.reason}")
                    break
                if ran and stage.name == "poses_colmap":
                    fallback_tried = False  # new frames or params: the fallback may help this reconstruction
                if ran:
                    summary = ", ".join(f"{k}={v}" for k, v in ctx.metrics.items() if k not in ("reasons",))
                    self.log(f"s{attempt.seed} {stage.name}: done  {summary}")
            else:
                attempt.status, attempt.stage = "passed", ""
        attempt.poses = stages.poses.active_source(path)
        metrics = json.loads((path / "metrics.json").read_text()) if (path / "metrics.json").exists() else {}
        attempt.gate = {k: v for k, v in metrics.get("gate", {}).items() if k not in ("reasons",)}
        attempt.eval_psnr = metrics.get("train", {}).get("eval_psnr") if attempt.status == "passed" else None
        attempt.gaussians = metrics.get("export", {}).get("n_gaussians") if attempt.status == "passed" else None
        attempt.seconds = round(time.monotonic() - t0, 1)
        if attempt.status == "passed":
            self.log(f"s{attempt.seed}: PASSED, eval PSNR {attempt.eval_psnr}")

    async def _execute_leased(self, attempt: Attempt, stage: stages.Stage, path: Path, params: dict[str, Any],
                              ctx: stages.Ctx, prefs: list[int], priority: int) -> bool:
        # Later stages first (priority -order): finish attempts in flight before starting new videos.
        attempt.stage = f"{stage.name} (waiting for a GPU)"
        self.job.save()
        async with self.pool.lease(prefs, priority=priority) as gpu:
            attempt.stage = stage.name
            self.job.save()
            ctx.gpu = attempt.gpus[stage.name] = gpu
            return await asyncio.to_thread(stage.execute, path, params, ctx)

    async def _try_fallback(self, attempt: Attempt, path: Path, ctx: stages.Ctx, priority: int) -> bool:
        """After the gate rejected COLMAP's cameras: pose the frames with Depth Anything 3, refine
        them with COLMAP, and make those the active cameras. True if the gate should judge them."""
        fallback = stages.FALLBACK
        params = fallback.defaults | attempt.stage_params(self.job.spec, fallback.name)
        if not params["enabled"] or not (path / "poses" / "colmap" / "database.db").exists():
            return False  # off, or no COLMAP matches to refine against
        self.log(f"s{attempt.seed}: the gate rejected COLMAP's cameras; trying the pose fallback (Depth Anything 3)")
        try:
            await self._execute_leased(attempt, fallback, path, params, ctx, self.job.spec.post_gpus, priority)
        except stages.StageFailed as e:  # the attempt goes on as if there were no fallback; Cancelled passes through
            self.log(f"s{attempt.seed}: pose fallback failed: {e}")
            return False
        stages.poses.activate(path, "fallback")
        return True

    async def _fill_gaps(self, attempt: Attempt, path: Path, ctx: stages.Ctx, priority: int) -> bool:
        """After a gate rejection: regenerate the jumps of the camera path, once per attempt.
        True if frames were filled and the pipeline should run again."""
        fill = stages.GAPFILL
        params = fill.defaults | attempt.stage_params(self.job.spec, fill.name) | {"seed": attempt.seed}
        if not params["enabled"] or stages.gapfill.applied(path):
            return False  # off, or already filled and still rejected
        gaps, why = stages.gapfill.plan(path, params)
        if not gaps:
            self.log(f"s{attempt.seed}: no gap fill ({why})")
            return False
        self.log(f"s{attempt.seed}: the gate failed only on jumps; filling "
                 + ", ".join(f"{g.first} -> {g.last} ({g.deg:.0f} degrees)" for g in gaps))
        try:
            # A video model: the video GPUs, at the gate's priority (finish this attempt first).
            await self._execute_leased(attempt, fill, path, params, ctx, self.job.spec.video_gpus, priority)
        except stages.StageFailed as e:  # the attempt stays rejected; Cancelled passes through
            self.log(f"s{attempt.seed}: gap fill failed: {e}")
            return False
        manifest = stages.gapfill.applied(path)
        attempt.filled = stages.gapfill.summary(manifest) if manifest else []
        return bool(manifest)

    def _progress(self, attempt: Attempt) -> Callable[[str, float, str], None]:
        last: dict[str, float] = {}

        def progress(stage: str, frac: float, msg: str) -> None:
            self._emit(attempt, "progress", stage, frac=round(frac, 4), msg=msg)
            if frac >= 1.0 or frac - last.get(stage, -1.0) >= 0.1:
                last[stage] = frac
                self.log(f"s{attempt.seed} {stage}: {frac:4.0%} {msg}")

        return progress


def describe(job: Job) -> str:
    """A table of the job's attempts, best first."""
    rank = {seed: i + 1 for i, seed in enumerate(job.ranking)}
    rows = sorted(job.attempts, key=lambda a: (rank.get(a.seed, 99), a.status != "running"))
    lines = [f"job {job.path.name}: {job.status}, {len(job.ranking)} passed of {len(job.attempts)} attempts"
             + (f", best seed {job.ranking[0]}" if job.ranking else "")]
    for a in rows:
        g = a.gate
        geo = (f"sweep {g['azimuth_coverage']:.0f}°, {g['n_views']} views"
               if "azimuth_coverage" in g else "")
        psnr = f"PSNR {a.eval_psnr:.1f}" if a.eval_psnr is not None else ""
        if a.gaussians is not None:
            geo = f"{geo}, {a.gaussians / 1000:.0f}K splats"
        where = a.reason or (a.stage and f"at {a.stage}") or ""
        lines.append(f"  {'#' + str(rank[a.seed]) if a.seed in rank else '  '} seed {a.seed:<10} "
                     f"{a.status:<9} {psnr:<10} {geo:<36} {where}".rstrip())
    return "\n".join(lines)


async def run_jobs(jobs: list[Job], log: Log, gpus: list[int]) -> list[Job]:
    """Run several jobs at once on one GPU pool, e.g. a parameter sweep.
    Earlier jobs' videos are queued first; later stages still outrank videos."""
    pool, cancel = GpuPool(gpus), threading.Event()
    loop = asyncio.get_running_loop()

    def interrupt() -> None:
        if not cancel.is_set():
            log("cancelling all jobs (giro job resume continues each one)")
            cancel.set()

    loop.add_signal_handler(signal.SIGINT, interrupt)
    try:
        def prefixed(job: Job) -> Log:
            name = job.path.name.split("-", 2)[-1]  # drop the timestamp
            return lambda msg: log(f"{name} {msg}")

        return list(await asyncio.gather(*(Runner(job, prefixed(job), pool, cancel).run() for job in jobs)))
    finally:
        loop.remove_signal_handler(signal.SIGINT)
        for g in gpus:
            server.stop_if_idle(g)
